### ISSUE TITLE
Regarding issue in GeneratingDatasets.py file

### ISSUE THREAD

**Issue by determinedrover** [arobertson38/LocalGlobalDecompositions#2]
On running the GeneratingDatasets.py file for generating the dataset for NBSA material I'm coming across this error

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-33-5c48a91cf30f>](https://localhost:8080/#) in <cell line: 136>()
    146 
    147         # running the method
--> 148         make_NBSA_datasets(
    149             micros = micros,
    150             patch_size = patch_size,

2 frames
[/content/LocalGlobalDecompositions/LGDGeneration/MKS/utils/PCA.py](https://localhost:8080/#) in train_PCA(data, save_loc, components)
    136     transformed = pca.fit_transform(stats)
    137 
--> 138     with open(save_loc, 'wb') as f:
    139         pickle.dump(pca, f)
    140 

FileNotFoundError: [Errno 2] No such file or directory: './MKS/utils/ReferenceDataTestingSuite/pcaModel_NBSA_index14_ps40_256.pkl'

This is when the code was run in google colab. I think there is some issue in generating the ReferenceDataTestingSuite directory.

Kindly help me resolve this issue 
Thanks in advance

**Comment by arobertson38** [comment]
Hello! Thanks for bring this to my attention. The method that you are trying to run has two purposes. First, it generates a microstructure patch dataset for training. Second, it generates the necessary files for running the error scripts utilized by the code. From the output that you have, it seems like the code is erroring on the second step (can you confirm that patch dataset is being generated?). 

The error in the second step seems to be occuring when the code goes to save the files necessary for the error computation. Its been hardcoded to save into a folder called "ReferenceDataTestingSuite". This folder should be inside MKS/utils. However, I forgot to include the folder. If you add the folder to this location it should run. 

When I get a chance, I will also add some code to automatically check for the folder and create it if its missing. 

Let me know if this fixes things.

**Comment by determinedrover** [comment]
Hello Andreas , 

Thanks for fixing that issue.

I was trying another thing with this repository. I have an input SEM image different from the reference images used in this repository and wanted to know how to train the model on that dataset to help me generate the synthetic microstructure for the SEM image. Kindly let me know the procedure for generating it as I'm a bit confused about how to train the model and generate it after generating the dataset using the GeneratingDatasets.py file


Thanks in advance

**Comment by arobertson38** [comment]
The entire library will certainly work with a new image. However, the framework is designed to generate microstructures represented as phase maps (i.e., where each phase has an indicator function associated with it). Therefore, you will need to make sure the SEM image is segmented. 

Once its segmented, you can follow the following steps:
1. Generate a patch dataset by adapting make_NBSA_dataset or make_TI_dataset (starting with either one should work fine) in the GeneratingDatasets.py file. (you will need to play around with the optimal patch size for your problem). To get just the baseline training working, you may want to comment out the code for making the error files. 
2. Create a config file for your problem. I recommend starting from one of the baseline files. The main things you'll need to change are: data_location, image_size, channels (channels should be equal to the number of phases you want the model to generate). After that, you might want to play around with which model you use depending on the complexity of the features that you are generating. 
3. Adapt the jobs.bat file to call the config file that you want. 
4. Start running!

As a warning, the patch size can have a huge effect on the quality of the model. You need to think about what size features are important to your system. Your patch size should reflect that. 

Andreas

**Comment by determinedrover** [comment]
Thanks for the procedure. I'll try as you suggested
